### ISSUE TITLE
Persisted SQL System Data

### ISSUE THREAD

**Issue by jmiedreich** [tfenster/mssql-image#10]
Hello,

First I wanted to thank you the SQL docker images for windows, its been a great help for me.  

Can you provide some guidance on how to get this running with the master DB's persisted using docker-compose? Or perhaps provide some tips on how to get the locations changed to another folder other then program files which you can not reference in a docker-compose file due to the spaces?

Thanks in advance,
Jeremy

**Comment by tfenster** [comment]
@jmiedreich thanks for your feedback, very much appreciated!

For your question: If I am not misunderstanding your question, you can definitely mount a path in a docker-compose file with a blank. E.g. use this

```
version: '3.7'

services:
  nano:
    image: mcr.microsoft.com/powershell:lts-nanoserver-ltsc2022
    container_name: nano
    volumes:
      - source: 'c:\Program Files'
        target: 'c:\host program files'
        type: bind
    entrypoint: ['pwsh', '-c', 'ping -t localhost']
```

to create a container with "c:\host program files" in the container pointing at "c:\program files" on the host. If you do a `docker exec -ti nano cmd` and then run `dir "host program files"`, you should see something like this:

```
PS C:\Users\tfenster> docker exec -ti nano cmd
Microsoft Windows [Version 10.0.20348.473]
(c) Microsoft Corporation. All rights reserved.

C:\>dir "host program files"
 Volume in drive C has no label.
 Volume Serial Number is DC51-DD85

 Directory of C:\host program files

02/23/2022  12:37 PM    <DIR>          .
02/10/2022  05:03 PM    <DIR>          Application Verifier
05/08/2021  08:27 AM    <DIR>          Common Files
02/10/2022  11:14 AM    <DIR>          dotnet
02/10/2022  10:57 AM    <DIR>          Git
05/08/2021  08:15 AM    <DIR>          Internet Explorer
05/08/2021  08:15 AM    <DIR>          ModifiableWindowsApps
02/10/2022  11:41 AM    <DIR>          nodejs
02/10/2022  10:48 AM    <DIR>          OpenSSH-Win64
02/23/2022  12:37 PM    <DIR>          PackageManagement
02/23/2022  12:36 PM    <DIR>          PowerShell
02/10/2022  05:09 PM    <DIR>          Windows Defender
02/03/2022  12:48 AM    <DIR>          Windows Defender Advanced Threat Protection
05/08/2021  09:33 AM    <DIR>          Windows NT
02/23/2022  12:37 PM    <DIR>          WindowsPowerShell
               0 File(s)              0 bytes
              15 Dir(s)  43,564,584,960 bytes free
```

But that is probably not the main question. To move the master db, I would try to use a script like explained here https://www.mikefal.net/2015/12/09/moving-your-master-database-with-powershell/ and it to a folder that is bound to a host folder. Does that make sense for you?
