### ISSUE TITLE
Debugging in SQL

### ISSUE THREAD

**Issue by DatKyle** [tfenster/mssql-image#7]
Hi,

I've just been having a play around with the SQL image and noticed that it's not possible to debug SQL in the containers:
![DebuggerError](https://user-images.githubusercontent.com/19267276/151200350-22c0f047-ad93-427d-b089-8e42cfb8900e.png)
I've been trying to find out if there is a specific port we need to have in the binds but I'm not able to find any 😕
<br/>
<br/>

Do you have any ideas about this or if it is possible or not?

**Comment by tfenster** [comment]
Can you share how you start the container?

**Comment by DatKyle** [comment]
Sure, I'm running it as part of a compose project:
```yml
version: "3.9"
services:
  TravellerSQL:
    #hostname: ccc-sql
    image: "tobiasfenster/mssql-server-dev-unsupported:2019-cu12"
    ports:
      - "14331:1433"
    environment:
      - sa_password=Password123
      - ACCEPT_EULA=Y
      - attach_dbs=[{'dbName':'db1','dbFiles':['C:\\temp\\db1\\Data\\db2.mdf','C:\\temp\\db1\\Log\\db2.ldf']},{'dbName':'db2','dbFiles':['C:\\temp\\db2\\Data\\db2.mdf','C:\\temp\\db2\\Log\\db2.ldf']}]
    volumes:
      - .\Database\clone\Docker_db1:C:\temp\db1
      - .\Database\clone\Docker_db2:C:\temp\db2
    dns:
      - 172.0.0.0
      - 172.0.0.1
    dns_search: dns.com
    deploy:
      resources:
        limits:
          memory: 4G
```
